language: python
python: 3.8

install:
  - "wget https://exiftool.org/Image-ExifTool-12.52.tar.gz"
  - "gzip -dc Image-ExifTool-12.52.tar.gz | tar -xf -"
  - "cd Image-ExifTool-12.52"
  - "perl Makefile.PL"
  - "sudo make install"
  - "cd .."
  - 'curl -sSL https://install.python-poetry.org | python3 -'
  - 'poetry self update 1.4.0'
  - "poetry install"

script:
  - poetry run pre-commit run --all-files
  - poetry run pytest
