language: python
python: 3.8

install:
  - "wget https://exiftool.org/Image-ExifTool-12.40.tar.gz"
  - "gzip -dc Image-ExifTool-12.40.tar.gz | tar -xf -"
  - "cd Image-ExifTool-12.40"
  - "perl Makefile.PL"
  - "sudo make install"
  - "pip install poetry"
  - "poetry install"

script:
  - poetry run pre-commit run --all-files
  - poetry run pytest tests