language: python
python: 3.8

install:
  - wget https://exiftool.org/Image-ExifTool-12.89.tar.gz
  - gzip -dc Image-ExifTool-12.89.tar.gz | tar -xf -
  - cd Image-ExifTool-12.89
  - perl Makefile.PL
  - sudo make install
  - cd ..
  - curl -sSL https://install.python-poetry.org | python3 -
  - export PATH="/root/.local/bin:$PATH"
  - poetry self update 1.5.1
  - poetry install
  - pip install "urllib3>=1.0.0,<2.0.0"

script:
  - poetry run pre-commit run --all-files
  - poetry run pytest
