name: imgcorrect-venv
channels:
  - conda-forge
dependencies:
  - python=3.8
  # dev dependencies
  - pytest
  - pre_commit
  - sphinx
  - sphinx_rtd_theme
  - m2r
  - pip
  - pipenv
  # main dependencies
  - Pillow
  - numpy
  - tifffile
  - pandas
  - tqdm
  - imageio
  - imagecodecs
  # subpackage dependencies
  # Sentera dependencies
  - pip:
    - git+https://github.com/SenteraLLC/py-image-metadata-parser.git@add-dji-ils
