[tool.poetry]
name = "correct6x"
version = "1.1.0"
description = "Library to perform various corrections on native 6X imagery"
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Pillow = "^8.1.2"
numpy = "^1.20.1"
tifffile = "^2021.3.16"
pandas = "^1.2.3"
tqdm = "^4.59.0"
imgparse = {git = "ssh://git@github.com/SenteraLLC/py-image-metadata-parser.git", tag = "v1.9.2"}
imgreg = {git = "git@github.com:SenteraLLC/py-image-registration.git"}
opencv-python = "^4.5.1"
opencv-contrib-python = "^4.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
