name: Lint and Test
on:
  push:
    branches-ignore:
      [master]

jobs:
  lint:
    name: Lint and test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0

      - name: Install Exiftool
        run: |
          wget https://exiftool.org/Image-ExifTool-12.52.tar.gz
          gzip -dc Image-ExifTool-12.52.tar.gz | tar -xf -
          cd Image-ExifTool-12.52
          perl Makefile.PL
          sudo make install
          cd ..

      - name: Install poetry dependency manager
        run: pipx install poetry==1.5.1

      - name: Setup Python environment
        uses: actions/setup-python@d27e3f3d7c64b4bbf8e4abfb9b63b83e846e0435 # v4.5.0
        with:
          cache: poetry

      - name: Install SSH keys for private dependencies
        uses: webfactory/ssh-agent@d4b9b8ff72958532804b70bbe600ad43b36d5f2e # v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_SENTERA_TRAVIS }}
          log-public-key: false

      - name: Enforce style guides and lint rules
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0

      - name: Install dependencies
        run: poetry install

      - name: Run unit tests
        run: poetry run pytest

      - name: Confirm repo is clean
        run: git diff-index --quiet HEAD
