name: Main branch
on:
  push:
    branches: master

jobs:
  version:
    name: Generate a version
    runs-on: ubuntu-20.04
    steps:
    - id: version
      name: Generate a date-based version
      run: echo "version=$(date +'%Y.%m%d.%H%M%S')" >> "$GITHUB_OUTPUT"
    outputs:
      version: ${{ steps.version.outputs.version }}

  release:
    name: Create a GitHub Release
    needs: [version]
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Create a GitHub Release
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          result-encoding: string
          retries: 3
          script: |
            github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "${{needs.version.outputs.version}}",
              target_commitish: context.sha,
              name: "${{needs.version.outputs.version}}",
              generate_release_notes: true
            })
