name: Create GitHub Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  release:
    name: Create GitHub Release
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TOML Reader
        id: read_toml
        uses: SebRollen/toml-action@2bd04b06a3ebc3e6a3eb6060de115710cad16cd6 #v1.0.2
        with:
          file: 'pyproject.toml'
          field: 'tool.poetry.version'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install .

      - name: Build EXEs
        shell: pwsh
        run: |
          pyinstaller correct_images_onefile.spec --noconfirm --clean
          pyinstaller get_corrections_onefile.spec --noconfirm --clean
          pyinstaller correct_images_gui_onefile.spec --noconfirm --clean

      - name: Define TAG
        shell: pwsh
        run: |
          "TAG=v${{ steps.read_toml.outputs.value }}" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.TAG }}
          target_commitish: ${{ github.sha }}
          generate_release_notes: true
          files: |
            dist/ImageryCorrector.exe
            dist/GetCorrectionsCsv.exe
            dist/Sentera Radiometric Corrections GUI.exe
